/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./CW20Base.client";
import * as _2 from "./CW20Base.message-composer";
import * as _4 from "./RotoStaking.client";
import * as _5 from "./RotoStaking.message-composer";
import * as _7 from "./RotoSwapRoto.client";
import * as _8 from "./RotoSwapRoto.message-composer";
import * as _10 from "./RotoSwapOthers.client";
import * as _11 from "./RotoSwapOthers.message-composer";
export declare namespace contracts {
    const CW20Base: {
        CW20BaseMessageComposer: typeof _2.CW20BaseMessageComposer;
        CW20BaseQueryClient: typeof _1.CW20BaseQueryClient;
        CW20BaseClient: typeof _1.CW20BaseClient;
    };
    const RotoStaking: {
        RotoStakingMessageComposer: typeof _5.RotoStakingMessageComposer;
        RotoStakingQueryClient: typeof _4.RotoStakingQueryClient;
        RotoStakingClient: typeof _4.RotoStakingClient;
    };
    const RotoSwapRoto: {
        RotoSwapRotoMessageComposer: typeof _8.RotoSwapRotoMessageComposer;
        RotoSwapRotoQueryClient: typeof _7.RotoSwapRotoQueryClient;
        RotoSwapRotoClient: typeof _7.RotoSwapRotoClient;
    };
    const RotoSwapOthers: {
        RotoSwapOthersMessageComposer: typeof _11.RotoSwapOthersMessageComposer;
        RotoSwapOthersQueryClient: typeof _10.RotoSwapOthersQueryClient;
        RotoSwapOthersClient: typeof _10.RotoSwapOthersClient;
    };
}
