/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CW20Base.types";
import * as _1 from "./CW20Base.client";
import * as _2 from "./CW20Base.message-composer";
import * as _3 from "./RotoStaking.types";
import * as _4 from "./RotoStaking.client";
import * as _5 from "./RotoStaking.message-composer";
import * as _6 from "./RotoSwapRoto.types";
import * as _7 from "./RotoSwapRoto.client";
import * as _8 from "./RotoSwapRoto.message-composer";
import * as _9 from "./RotoSwapOthers.types";
import * as _10 from "./RotoSwapOthers.client";
import * as _11 from "./RotoSwapOthers.message-composer";
export namespace contracts {
  export const CW20Base = { ..._0,
    ..._1,
    ..._2
  };
  export const RotoStaking = { ..._3,
    ..._4,
    ..._5
  };
  export const RotoSwapRoto = { ..._6,
    ..._7,
    ..._8
  };
  export const RotoSwapOthers = { ..._9,
    ..._10,
    ..._11
  };
}